# Generated by Django 4.1 on 2022-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productgallery_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 1'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 2'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 3'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 4'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 5'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 6'),
        ),
    ]
