# Generated by Django 4.1.5 on 2023-02-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
        ('home_module', '0006_startdate_num_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='')),
                ('end_date', models.DateField(verbose_name='')),
                ('booked_on', models.DateField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='')),
                ('email', models.CharField(max_length=500, verbose_name='')),
                ('massage', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=60, verbose_name='')),
                ('room_type', models.CharField(max_length=60, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('price', models.CharField(max_length=5000, verbose_name='')),
                ('score', models.IntegerField(verbose_name='')),
                ('start_date', models.DateField()),
                ('room_image', models.ImageField(upload_to='uploads')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.user', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='startdate',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndDate',
        ),
        migrations.DeleteModel(
            name='StartDate',
        ),
        migrations.DeleteModel(
            name='USer',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.rooms', verbose_name=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.customer', verbose_name=''),
        ),
    ]
