# Generated by Django 4.1.5 on 2023-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0009_alter_booking_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='massage_admin',
            field=models.TextField(default=1, verbose_name='متن ادمین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='see_text',
            field=models.BooleanField(default=False, verbose_name='دیده شده / نشده'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='score',
            field=models.IntegerField(verbose_name='شناسه'),
        ),
    ]
