# Generated by Django 4.1.5 on 2023-02-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_admin'),
        ('home_module', '0010_contact_massage_admin_contact_see_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='user_module.admin', verbose_name='ادمین'),
            preserve_default=False,
        ),
    ]
