# Generated by Django 4.1.5 on 2023-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0023_remove_contact_admin_remove_contact_massage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='ایمیل'),
        ),
    ]
