# Generated by Django 4.1.5 on 2023-03-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0024_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=1000, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'کصشر',
                'verbose_name_plural': 'کصشرها',
            },
        ),
    ]
