# Generated by Django 4.1.5 on 2023-03-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0030_contactusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
