# Generated by Django 4.1.5 on 2023-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0032_delete_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام')),
                ('email', models.EmailField(max_length=500, verbose_name='ایمیل')),
                ('massage', models.CharField(max_length=1000, verbose_name='متن')),
                ('massage_admin', models.CharField(max_length=1000, verbose_name='متن ادمین')),
                ('see_text', models.BooleanField(default=False, verbose_name='دیده شده / نشده')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباتاط با ما',
            },
        ),
    ]
