# Generated by Django 4.1.5 on 2023-03-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0038_contact_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage_admin',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن ادمین'),
        ),
    ]
