# Generated by Django 4.1.5 on 2023-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0039_alter_contact_massage_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now_add=True, verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.IntegerField(verbose_name='تعداد اتاق ها'),
        ),
    ]
