# Generated by Django 4.1 on 2022-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_remove_user_mobile_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emile_active_code',
            new_name='email_active_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تصویر آواتار'),
        ),
    ]
