# Generated by Django 4.1 on 2022-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_articlecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
