# Generated by Django 4.1.5 on 2023-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_alter_customer_options_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('email', models.CharField(max_length=500, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=300, verbose_name='تلفن همراه')),
                ('gender', models.CharField(max_length=300, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'ادمین',
                'verbose_name_plural': 'ادمین ها',
            },
        ),
    ]
