# Generated by Django 4.1.5 on 2023-03-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0034_contact_remove_booking_user_id_remove_rooms_manager'),
        ('user_module', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
