# Generated by Django 4.1.5 on 2023-03-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
