# Generated by Django 4.1 on 2022-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 1'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 2'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_gallery', verbose_name='تصویر محصول شماره 3'),
        ),
    ]
