# Generated by Django 4.1 on 2022-12-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_remove_productgallery_image_productgallery_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='image6',
        ),
    ]
