# Generated by Django 4.1.5 on 2023-02-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'تنظیمات کاربر', 'verbose_name_plural': 'تنظیمات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
