# Generated by Django 4.1 on 2022-12-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_alter_slider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس لینک')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_ditail', 'صفحه جزیات محصولات'), ('about_us', 'صفحه درباره ما')], max_length=200, verbose_name='محل قرار گیری')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
