# Generated by Django 4.1.5 on 2023-01-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن / نبودن'),
        ),
    ]
