# Generated by Django 4.1.5 on 2023-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='enddate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن / نبودن'),
        ),
        migrations.AddField(
            model_name='startdate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن / نبودن'),
        ),
    ]
