# Generated by Django 4.1.5 on 2023-01-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_rename_active_user_is_active_enddate_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startdate',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndDate',
        ),
        migrations.DeleteModel(
            name='StartDate',
        ),
        migrations.DeleteModel(
            name='USer',
        ),
    ]
