# Generated by Django 4.1.5 on 2023-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startdate',
            name='num_rooms',
            field=models.IntegerField(blank=True, default=1, verbose_name='تعداد اتاق ها'),
        ),
    ]
