# Generated by Django 4.1.5 on 2023-02-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_customer_address_alter_customer_email_and_more'),
        ('home_module', '0007_booking_contact_rooms_remove_startdate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.rooms', verbose_name='تعداد اتاق ها'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.customer', verbose_name='ای دی کاربران'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=500, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.CharField(max_length=500, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.user', verbose_name='کاربران'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.CharField(max_length=5000, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(upload_to='uploads', verbose_name='عکس اتاق ها'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(max_length=60, verbose_name='نوع اتاق'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rooms',
            field=models.CharField(max_length=60, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ ورود'),
        ),
    ]
