# Generated by Django 4.1.5 on 2023-02-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_admin'),
        ('home_module', '0011_contact_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیمات غذا',
                'verbose_name_plural': 'تنظیمات غذا ها',
            },
        ),
        migrations.CreateModel(
            name='SettingSite_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیم بالای سایت',
                'verbose_name_plural': 'تنظیمات بالای سایت',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.admin', verbose_name='توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_module.user', verbose_name='کاربران'),
        ),
    ]
