# Generated by Django 4.1.5 on 2023-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0012_foodshotel_settingsite_header_alter_contact_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite_header',
            name='is_main_setting',
            field=models.BooleanField(default=True, verbose_name='تنظیمات اصلی'),
        ),
        migrations.AlterField(
            model_name='settingsite_header',
            name='description',
            field=models.CharField(default='test', max_length=1000, verbose_name='توضیحات'),
        ),
    ]
