# Generated by Django 4.1.5 on 2023-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0015_alter_settingsite_header_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsite_header',
            name='address',
            field=models.CharField(max_length=10000, verbose_name='آدرس'),
        ),
    ]
