# Generated by Django 4.1.5 on 2023-03-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0018_alter_settingsite_header_description_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshotel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
