# Generated by Django 4.1.5 on 2023-03-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0019_foodshotel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
