# Generated by Django 4.1.5 on 2023-03-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0020_aboutsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moshtari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
    ]
