# Generated by Django 4.1.5 on 2023-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0021_moshtari'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='cos', max_length=300, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='moshtari',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='moshtari',
            name='title',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
    ]
