# Generated by Django 4.1.5 on 2023-03-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_admin'),
        ('home_module', '0026_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.admin', verbose_name='توسط ادمین'),
        ),
        migrations.AddField(
            model_name='contact',
            name='massage',
            field=models.CharField(max_length=1000, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='contact',
            name='massage_admin',
            field=models.CharField(max_length=1000, verbose_name='متن ادمین'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='uploads/site_setting', verbose_name='لوگو سایت'),
        ),
    ]
