# Generated by Django 4.1.5 on 2023-03-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0027_delete_contactus_remove_contact_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='admin',
        ),
    ]
