# Generated by Django 4.1.5 on 2023-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0028_remove_contact_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.CharField(max_length=1000, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='massage_admin',
            field=models.CharField(max_length=1000, verbose_name='متن ادمین'),
        ),
    ]
