# Generated by Django 4.1.5 on 2023-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0031_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
    ]
