# Generated by Django 4.1.5 on 2023-03-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0034_contact_remove_booking_user_id_remove_rooms_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSite',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
        migrations.DeleteModel(
            name='FoodsHotel',
        ),
        migrations.DeleteModel(
            name='Moshtari',
        ),
        migrations.DeleteModel(
            name='SettingSite_header',
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
